name: Publish release to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the release commit
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python packages needed for build and upload
      run: |
        python -m pip install build twine
    - name: Build sdist and wheel
      run: |
        python -m build
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m twine check --strict dist/*
        python -m twine upload dist/*